#!/usr/bin/env sh

# taps

# packages
brew install adns
brew install aom
brew install autoconf
brew install cairo
brew install ffmpeg
brew install flac
brew install fontconfig
brew install freetype
brew install frei0r
brew install fribidi
brew install gdbm
brew install gettext
brew install ghostscript
brew install giflib
brew install glib
brew install gmp
brew install gnu-getopt
brew install gnupg
brew install gnutls
brew install go
brew install graphite2
brew install harfbuzz
brew install htop
brew install icu4c
brew install jpeg
brew install lame
brew install leptonica
brew install libass
brew install libassuan
brew install libbluray
brew install libevent
brew install libffi
brew install libgcrypt
brew install libgpg-error
brew install libidn2
brew install libksba
brew install libogg
brew install libpng
brew install libsamplerate
brew install libsndfile
brew install libsoxr
brew install libtasn1
brew install libtiff
brew install libtool
brew install libunistring
brew install libusb
brew install libvorbis
brew install libvpx
brew install libyaml
brew install libzip
brew install little-cms2
brew install lua
brew install lzo
brew install ncurses
brew install nettle
brew install npth
brew install opencore-amr
brew install openjpeg
brew install openssl
brew install opus
brew install p11-kit
brew install pandoc
brew install pango
brew install pcre
brew install pdf2htmlex
brew install perl
brew install pinentry
brew install pixman
brew install pkg-config
brew install python
brew install python@2
brew install readline
brew install rtmpdump
brew install rubberband
brew install ruby
brew install sdl2
brew install snappy
brew install speex
brew install sqlite
brew install tesseract
